### ISSUE TITLE
Help: Cuda Out of Memory with NVidia 3080 with 10GB VRAM

### ISSUE THREAD

**Issue by tamueller** [CompVis/stable-diffusion#232]
Hi,
I just installed stable-diffusion using this tutorial: https://www.howtogeek.com/830179/how-to-run-stable-diffusion-on-your-pc-to-generate-ai-images/ using [sd-v1-4.ckpt](https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt)

When I start it, I get: 
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 10.00 GiB total capacity; 7.13 GiB already allocated; 0 bytes free; 7.73 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I installed NVITop, and it says 540MiB / 10240 MiB before I start the script, and I closed everything that consumed VRAM.
The max I can run is 384x384, where I get 8810 MiB / 10240MiB used.

I tried to remove the NSFW filter to save some VRAM, but with no effect on the memory usage. (I still use 8802MiB, is it really only 2MiB difference?)

I know that there is an optimized version that trades VRAM usage for speed, but since I actually have 10GB of VRAM, I'd like to use the normal version, which "should" run on 3080 with 10GB, shouldn't it?

**Comment by ithotline3** [comment]
Use this: https://github.com/basujindal/stable-diffusion

**Comment by tamueller** [comment]
I tried the "optimized" version of basujindal but it's about a factor of 5 slower. That's why I was asking excplicitly on how to get the normal version running on this card (or why it's not possible)

**Comment by 7ih** [comment]
You can try removing the safety check, which takes up 2gb of vram

replace scripts/txt2img.py with this:
https://github.com/JustinGuese/stable-diffusor-docker-text2image/blob/master/txt2img.py

**Comment by tamueller** [comment]
As written in the Original Post, I already tried to remove the NSFW filter.
I found a solution that works quite good for me: The WEBUI fork has some optimizations included (https://github.com/sd-webui/stable-diffusion-webui/) that allow me to run it on 512x512, but at nearly the same speed as the original repo.

**Comment by AlphaRayReal** [comment]
> As written in the Original Post, I already tried to remove the NSFW filter. I found a solution that works quite good for me: The WEBUI fork has some optimizations included (https://github.com/sd-webui/stable-diffusion-webui/) that allow me to run it on 512x512, but at nearly the same speed as the original repo.

this one is using the normal SD.  I can render up to 2048x768 with only 8 GB VRAM with basujindal.  With turbo mode up to 1536 x 832 max.  1024 x 1024 is no problem - and this is 4x bigger than 512x512.  With 10 GB VRAM you should render up to about 1536 x 1024 in turbo mode

**Comment by funfunnypl** [comment]
try to follow this one https://www.youtube.com/watch?v=OjOn0Q_U8cY 
it helped myself
