### ISSUE TITLE
How to generate MORE images?

### ISSUE THREAD

**Issue by MojoJojo43** [CompVis/stable-diffusion#237]
Hi all,

I am just trying to figure all of this out now that I have Diffusion up and running. Whenever I change the prompt to get more samples from something like this:

`python scripts/txt2img.py --prompt "my prompt" --plms --ckpt sd-v1-4.ckpt --skip_grid --n_samples 2 --outdir C:\Users\user\Pictures\Dream\Stable-Diffusion-Output`

to anything other than 2 like this:

`python scripts/txt2img.py --prompt "my prompt" --plms --ckpt sd-v1-4.ckpt --skip_grid --n_samples 3 --outdir C:\Users\user\Pictures\Dream\Stable-Diffusion-Output`

I keep receiving this error:

```
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

All I want is for the script to generate more than 4 images at a time, like maybe 10 or more.

What am I doing wrong?

Thanks!

**Comment by KostyaAtarik** [comment]
increase `--n_iter` to 5 leaving `--n_samples` being 2 to generate 10 images

**Comment by MojoJojo43** [comment]
> increase `--n_iter` to 5 leaving `--n_samples` being 2 to generate 10 images

Hi, yeah I should have stated that I already do that. Do you know what the issue is with the error from trying to generate more than just two images in a batch?

**Comment by KostyaAtarik** [comment]
What is your gpu? It most likely doesn't have enough memory to fit more images in a batch

**Comment by KostyaAtarik** [comment]
Check memory utilization for `--n_samples` being `1` and `2` and then you can somewhat interpolate it for `3`

**Comment by MojoJojo43** [comment]
> What is your gpu? It most likely don't have enough memory to fit more images in a batch

Yeah my GPU is a GTX 1080 Ti 11GB so that is probably the issue. I will be upgrading in the near future though so hopefully that resolves the issue.

Thanks for the input.

**Comment by MojoJojo43** [comment]
> Check memory utilization for `--n_samples` being `1` and `2` and then you can somewhat interpolate it for `3`

I am not sure how to definitively do that aside from looking at the task manager performance while generating the 2 samples and it says that CPU is at 22% and GPU is at 3 to 5%.

**Comment by KostyaAtarik** [comment]
It's 10.8/11.0 Gb of gpu memory being used so it's the limiting factor here

**Comment by MojoJojo43** [comment]
> It's 10.8/11.0 Gb of gpu memory being used so it's the limiting factor here. I also tried running SD at a server with 2080Ti (11 Gb too) and it can't fit more than 2 samples

I appreciate you verifying and clarifying. Just have to work with what I have now till I can get an upgrade. A Titan V would be nice :-)
